// <auto-generated />
using System;
using LearnSoftBE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LearnSoftBE.Migrations
{
    [DbContext(typeof(LearnDataContext))]
    [Migration("20220117221719_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("LearnSoftBE.Models.UserModels.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("ECTS")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClassId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("LearnSoftBE.Models.UserModels.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LearnSoftBE.Models.UserModels.Student", b =>
                {
                    b.HasBaseType("LearnSoftBE.Models.UserModels.User");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("LearnSoftBE.Models.UserModels.Tutor", b =>
                {
                    b.HasBaseType("LearnSoftBE.Models.UserModels.User");

                    b.Property<string>("Degree")
                        .HasColumnType("text");

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("LearnSoftBE.Models.UserModels.Class", b =>
                {
                    b.HasOne("LearnSoftBE.Models.UserModels.Student", null)
                        .WithMany("ClassesList")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearnSoftBE.Models.UserModels.Student", b =>
                {
                    b.HasOne("LearnSoftBE.Models.UserModels.User", null)
                        .WithOne()
                        .HasForeignKey("LearnSoftBE.Models.UserModels.Student", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearnSoftBE.Models.UserModels.Tutor", b =>
                {
                    b.HasOne("LearnSoftBE.Models.UserModels.User", null)
                        .WithOne()
                        .HasForeignKey("LearnSoftBE.Models.UserModels.Tutor", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearnSoftBE.Models.UserModels.Student", b =>
                {
                    b.Navigation("ClassesList");
                });
#pragma warning restore 612, 618
        }
    }
}
